name: 'Install AutoHotkey'
description: 'Downloads and installs AutoHotkey and adds it to PATH'
author: 'Tao Beloney'

inputs:
  version:
    description: 'Version of AutoHotkey to install (e.g. 2.0.19 or "latest")'
    required: false
    default: 'latest'
  destination:
    description: 'Directory to install AutoHotkey into (defaults to current working directory)'
    required: false
    default: ''

runs:
  using: 'composite'
  steps:
    - name: Run installer
      outputs:
        version:
          description: 'The version of AutoHotkey that was actually installed'
        ahk32:
          description: 'The full path to the installed AutoHotkey32.exe executable'
        ahk64:
          description: 'The full path to the installed AutoHotkey64.exe executable'
      shell: pwsh
      run: |
        $scriptPath = Join-Path ${{ github.action_path }} 'scripts/install-autohotkey.ps1'
        & $scriptPath -Version '${{ inputs.version }}' -Destination '${{ inputs.destination }}'

branding:
  icon: 'terminal'
  color: 'green'
